import DocPage from '@/components/DocPage';
import { RocketIcon } from '@/components/icons/NeonIcons';

export const metadata = {
  title: 'Documentation - Rangkum AI | Student Lab',
};

export default function RangkumDocumentationPage() {
  return (
    <DocPage
      title="Rangkum AI"
      tagline="Turn your study documents into complete & structured notes."
      badge="Documentation"
      icon={<RocketIcon size={38} />}
      color="var(--neon-cyan)"
      glow="rgba(34, 224, 255, 0.35)"
      overview="Rangkum AI is a tool that uses AI to summarize documents automatically. Just upload a PDF, DOCX, TXT, or Markdown file, and the AI arranges an executive summary, key points, glossary, memorization tips, and action items — ready for you to study or share."
      capabilities={[
        'Automatically summarize PDF, DOCX, TXT, and Markdown files.',
        'Complete output: executive summary, key points, glossary, memorization tips, and action items.',
        'Save results to history so you can open them again anytime.',
        'Copy, download as Markdown, or export as PDF.',
        'PDF paper size options: A5, B5, A4, and Folio.',
        'Word-by-word typing animation so results are easy to read.',
      ]}
      examples={[
        {
          title: 'Original File (Input)',
          badge: 'Input',
          fileUrl: '/docs/input-definisi-kup.pdf',
          fileName: '01. Definisi KUP.pdf',
          note: 'The raw document you upload',
        },
        {
          title: 'Summary Result (Output)',
          badge: 'Output',
          fileUrl: '/docs/hasil-rangkuman-a4.pdf',
          fileName: 'Perangkum Dokumen AI A4.pdf',
          note: 'Generated by Rangkum AI (A4)',
        },
      ]}
      sections={[
        {
          title: 'Getting started',
          body: [
            '1. Open the Rangkum AI menu (make sure you are logged in).',
            '2. Drag and drop a file, or click the upload area to choose a file from your device.',
            '3. Supported formats: PDF, DOCX, TXT, and Markdown, with a maximum size of 4MB.',
            '4. Click the "Summarize Now" button and wait for the AI to build the result.',
          ],
        },
        {
          title: 'Tips for best results',
          body: [
            'Use documents with clear text and good quality so the AI reads them accurately.',
            'If your file is too large, compress it first to stay under the 4MB limit.',
            'Take advantage of the glossary and action items for studying and review.',
          ],
        },
        {
          title: 'Saving & sharing',
          body: [
            'Every summary is automatically saved to your history.',
            'You can copy the text, download it as Markdown, or download it as PDF with your chosen paper size.',
            'Dark mode is available so it is comfortable to read day or night.',
          ],
        },
      ]}
      toolHref="/rangkum"
      toolLabel="Rangkum AI"
    />
  );
}
